"""Embedding Size Column changed 

Revision ID: 0871aad13015
Revises: a492ed7b24ab
Create Date: 2026-02-16 23:54:18.746253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0871aad13015'
down_revision = 'a492ed7b24ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
