"""Project ID Column type Changed again 

Revision ID: 59bee8e69eac
Revises: b65e7dea7691
Create Date: 2026-02-16 05:12:39.195495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bee8e69eac'
down_revision = 'b65e7dea7691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
