"""removed Columns from projects table

Revision ID: 782fa80e2392
Revises: e641d3df9c03
Create Date: 2026-02-16 04:31:41.244596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782fa80e2392'
down_revision = 'e641d3df9c03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'new_col')
    op.drop_column('projects', 'new_col')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('new_col', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('new_col', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
