"""Chunk ID Column type Changed 

Revision ID: a492ed7b24ab
Revises: 59bee8e69eac
Create Date: 2026-02-16 05:23:09.622263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a492ed7b24ab'
down_revision = '59bee8e69eac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
