"""Project ID Column type Changed

Revision ID: b65e7dea7691
Revises: 782fa80e2392
Create Date: 2026-02-16 05:07:18.525708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65e7dea7691'
down_revision = '782fa80e2392'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
