"""Embedding Size Column changed agnain 

Revision ID: d3cbb6ac3b4f
Revises: 0871aad13015
Create Date: 2026-02-17 04:09:15.003325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cbb6ac3b4f'
down_revision = '0871aad13015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
