"""Initial tables

Revision ID: e641d3df9c03
Revises: 
Create Date: 2026-02-11 03:14:20.934569

"""
from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision = 'e641d3df9c03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('new_col', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('new_col', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks')
    op.drop_table('projects')
    # ### end Alembic commands ###
