version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: pgvector
    ports:
      - "54329:5432"      
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pgvector_data:/var/lib/postgresql/18/docker
    restart: always

volumes:
  pgvector_data: